/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgm.telas.Cadastro;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sgm.dao.ContratoDAO;
import sgm.dao.MercadoDAO;
import sgm.dao.PessoaFisicaDAO;
import sgm.dao.PessoaJuridicaDAO;
import sgm.dao.PrefeituraDAO;
import sgm.dominio.Contrato;
import sgm.dominio.Mercado;
import sgm.dominio.Pessoa;
import sgm.dominio.PessoaFisica;
import sgm.dominio.PessoaJuridica;
import sgm.dominio.Prefeitura;
/**
 *
 * @author aligr
 */
public class CadastrarContrato extends javax.swing.JInternalFrame {

    
    
    public CadastrarContrato() {
        initComponents();
        this.ccMercado.removeAllItems();
        MercadoDAO mercadoDAO = new MercadoDAO();
        List<Mercado> mercados = mercadoDAO.listar();
        for(Mercado mercado : mercados){
            this.ccMercado.addItem(mercado.getNome());
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ccNDB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ccVDA = new javax.swing.JTextField();
        ccLocatario = new javax.swing.JComboBox<>();
        ccMercado = new javax.swing.JComboBox<>();
        ccDDI = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        ccDDF = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        btnPF = new javax.swing.JRadioButton();
        btnPJ = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Contratos");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("LOCATARIO:");

        jLabel3.setText("MERCADO:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("NÚMERO DO BOX:");

        jLabel5.setText("VALOR DO ALUGUEL:");

        ccLocatario.setToolTipText("SELECIONE");
        ccLocatario.setName(""); // NOI18N
        ccLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccLocatarioActionPerformed(evt);
            }
        });

        ccMercado.setToolTipText("");
        ccMercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccMercadoActionPerformed(evt);
            }
        });

        try {
            ccDDI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ccDDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccDDIActionPerformed(evt);
            }
        });

        jLabel6.setText("DATA DO INICIO:");

        try {
            ccDDF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ccDDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccDDFActionPerformed(evt);
            }
        });

        jLabel7.setText("DATA DO FIM:");

        buttonGroup1.add(btnPF);
        btnPF.setText("Pessoa Física");
        btnPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPFActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnPJ);
        btnPJ.setText("Pessoa Jurídica");
        btnPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ccMercado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ccVDA, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ccLocatario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ccNDB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(ccDDI, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ccDDF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(11, 11, 11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPF)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(btnPJ)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPF)
                    .addComponent(btnPJ))
                .addGap(8, 8, 8)
                .addComponent(ccLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ccMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccNDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccDDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccDDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccVDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        ccLocatario.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ContratoDAO contratoDAO = new ContratoDAO();
        PessoaFisicaDAO pfDAO = new PessoaFisicaDAO();
        PessoaJuridicaDAO pjDAO = new PessoaJuridicaDAO();
        MercadoDAO mercadoDAO = new MercadoDAO();
        
        List<PessoaFisica> pfs = pfDAO.listar();
        List<PessoaJuridica> pjs = pjDAO.listar();
        List<Mercado> mercados = mercadoDAO.listar();
        
        Pessoa locatario;
        
        if(this.btnPF.isSelected()){
            locatario = pfs.get(this.ccLocatario.getSelectedIndex());
        }else if(this.btnPJ.isSelected()){
            locatario = pjs.get(this.ccLocatario.getSelectedIndex());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um tipo de locatário: Pessoa Física ou Pessoa Jurídica.");
            return;
        }
        Mercado mercado = mercados.get(this.ccMercado.getSelectedIndex());
        int box = Integer.parseInt(this.ccNDB.getText());
        double valorAluguel = Double.parseDouble(ccVDA.getText());
        Contrato contrato = new Contrato(locatario, mercado, box, ccDDI.getText(), ccDDF.getText(), valorAluguel);
        try {
            contratoDAO.salvar(contrato);
            JOptionPane.showMessageDialog(null, "Contrato: \n" + contrato + "\n Cadastrado com sucesso!");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ccDDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccDDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccDDIActionPerformed

    private void ccDDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccDDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccDDFActionPerformed

    private void ccLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccLocatarioActionPerformed

    }//GEN-LAST:event_ccLocatarioActionPerformed

    private void btnPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPFActionPerformed
        this.ccLocatario.removeAllItems();
        PessoaFisicaDAO pfDAO = new PessoaFisicaDAO();
        List<PessoaFisica> locatariosPF = pfDAO.listar();
        for(PessoaFisica pf : locatariosPF){
            this.ccLocatario.addItem((pf.getNome())); 
        }
    }//GEN-LAST:event_btnPFActionPerformed

    private void btnPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPJActionPerformed
        this.ccLocatario.removeAllItems();
        PessoaJuridicaDAO pjDAO = new PessoaJuridicaDAO();
        List<PessoaJuridica> locatariosPJ = pjDAO.listar();
        for(PessoaJuridica pj : locatariosPJ){
            int posicao = this.ccLocatario.getItemCount();
            this.ccLocatario.addItem(pj.getNome());
        }
    }//GEN-LAST:event_btnPJActionPerformed

    private void ccMercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccMercadoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_ccMercadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnPF;
    private javax.swing.JRadioButton btnPJ;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField ccDDF;
    private javax.swing.JFormattedTextField ccDDI;
    private javax.swing.JComboBox<String> ccLocatario;
    private javax.swing.JComboBox<String> ccMercado;
    private javax.swing.JTextField ccNDB;
    private javax.swing.JTextField ccVDA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
