/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgm.telas.Consulta;

import sgm.telas.Cadastro.CadastrarPF;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import sgm.dao.PessoaFisicaDAO;
import sgm.dao.PrefeituraDAO;
import sgm.dominio.PessoaFisica;
import sgm.dominio.Prefeitura;
import sgm.telas.Cadastro.CadastrarPF;

/**
 *
 * @author aligr
 */
public class ConsultarPrefeitura extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarPrefeitura
     */
    public ConsultarPrefeitura() {
        initComponents();
        PrefeituraDAO prefeituraDAO = new PrefeituraDAO();
        List <Prefeitura> prefeituras = new ArrayList<>();
        Prefeitura prefeitura;
        prefeituras = prefeituraDAO.listar();
        prefeitura = prefeituras.get(0);
        this.apCnpj.setText(prefeitura.getCnpj());
        this.apCnpj.setEnabled(false);
        this.apEndereco.setText(prefeitura.getEndereco());
        this.apNome.setText(prefeitura.getNome());
        this.apNomef.setText(prefeitura.getNomeFantasia());
        this.apRL.setText(prefeitura.getRepresentanteLegal().getCpf());       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        apSalvar = new javax.swing.JButton();
        apCnpj = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        apEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apNome = new javax.swing.JTextField();
        apNomef = new javax.swing.JTextField();
        apRL = new javax.swing.JFormattedTextField();
        apCancelar = new javax.swing.JButton();
        apExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Prefeitura");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("CNPJ:");

        jLabel2.setText("NOME:");

        jLabel3.setText("NOME FANTASIA:");

        apSalvar.setText("Alterar");
        apSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apSalvarActionPerformed(evt);
            }
        });

        try {
            apCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        apCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apCnpjActionPerformed(evt);
            }
        });

        jLabel4.setText("ENDEREÇO:");

        jLabel5.setText("CPF DO REPRESENTANTE LEGAL:");

        try {
            apRL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        apRL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apRL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apRLActionPerformed(evt);
            }
        });

        apCancelar.setText("Cancelar");
        apCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apCancelarActionPerformed(evt);
            }
        });

        apExcluir.setText("Excluir");
        apExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(apCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apExcluir)
                .addGap(13, 13, 13))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(apRL, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(apNomef, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apCnpj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apNome, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apNomef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apSalvar)
                    .addComponent(apCancelar)
                    .addComponent(apExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apSalvarActionPerformed
        PessoaFisicaDAO pessoaFisicaDAO = new PessoaFisicaDAO();
        PrefeituraDAO prefeituraDAO = new PrefeituraDAO();
        String cpf = apRL.getText();
        PessoaFisica representanteLegal = pessoaFisicaDAO.consultar(cpf);
        if(representanteLegal == null){
            JOptionPane.showMessageDialog(null, "Representante Legal não cadastrado. "
                + "Cadastre os dados do Representante Legal.");
            JDesktopPane desktop = this.getDesktopPane();
            CadastrarPF telaRepresentanteLegal = new CadastrarPF(cpf);
            desktop.add(telaRepresentanteLegal);
            telaRepresentanteLegal.setVisible(true);
            return;
        }
        Prefeitura prefeitura = new Prefeitura(apCnpj.getText(), apNome.getText(), apNomef.getText(),
            apEndereco.getText(), representanteLegal);
        prefeituraDAO.alterar(prefeitura);
        JOptionPane.showMessageDialog(null, "Prefeitura: \n" + prefeitura + "\n Atualizada com sucesso!");
        this.dispose();
    }//GEN-LAST:event_apSalvarActionPerformed

    private void apCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apCnpjActionPerformed

    private void apRLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apRLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apRLActionPerformed

    private void apCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_apCancelarActionPerformed

    private void apExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apExcluirActionPerformed
        PrefeituraDAO prefeituraDAO = new PrefeituraDAO();
        Prefeitura prefeitura = prefeituraDAO.consultar(this.apCnpj.getText());
        try {  
            prefeituraDAO.excluir(prefeitura.getCnpj());
            JOptionPane.showMessageDialog(null, "Prefeitura: \n" + prefeitura + "\n Excluída com sucesso!");
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex.getMessage());
            this.dispose();
        }
    }//GEN-LAST:event_apExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apCancelar;
    private javax.swing.JFormattedTextField apCnpj;
    private javax.swing.JTextField apEndereco;
    private javax.swing.JButton apExcluir;
    private javax.swing.JTextField apNome;
    private javax.swing.JTextField apNomef;
    private javax.swing.JFormattedTextField apRL;
    private javax.swing.JButton apSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
