/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sgm.telas.Consulta;

import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import sgm.dao.MercadoDAO;
import sgm.dao.PrefeituraDAO;
import sgm.dominio.Prefeitura;
import sgm.dominio.Mercado;


/**
 *
 * @author diego
 */
public class ConsultarMercado extends javax.swing.JInternalFrame {

    private MercadoDAO mercadoDAO;
    private List<Mercado> mercados;
    private Mercado mercado;
    
    public ConsultarMercado() {
        initComponents();
        this.aMSel.removeAllItems();
        this.aMCNPJ.setEnabled(false);
        this.mercadoDAO = new MercadoDAO();
        mercados = mercadoDAO.listar();
        for(Mercado m : mercados){
            this.aMSel.addItem(m.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aMCanc = new javax.swing.JButton();
        aMCNPJ = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        aMEndereco = new javax.swing.JTextField();
        aMNome = new javax.swing.JTextField();
        aMNomef = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        aMTBox = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        aMSel = new javax.swing.JComboBox<>();
        aMAl = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consultar Mercado");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("CNPJ:");

        jLabel2.setText("NOME:");

        jLabel3.setText("NOME FANTASIA:");

        aMCanc.setText("Cancelar");
        aMCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMCancActionPerformed(evt);
            }
        });

        try {
            aMCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        aMCNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aMCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMCNPJActionPerformed(evt);
            }
        });

        jLabel4.setText("ENDEREÇO:");

        jLabel6.setText("Total de boxs:");

        aMTBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Selecione o mercado para consultar os dados:");

        aMSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMSelActionPerformed(evt);
            }
        });

        aMAl.setText("Alterar");
        aMAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMAlActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aMNomef)
                    .addComponent(aMEndereco)
                    .addComponent(aMNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aMSel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(aMCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(aMTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 124, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 159, Short.MAX_VALUE)
                                .addComponent(aMCanc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aMAl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aMSel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aMCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aMNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aMNomef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aMEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aMTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aMCanc)
                    .addComponent(aMAl)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aMCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMCancActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_aMCancActionPerformed

    private void aMCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMCNPJActionPerformed

    }//GEN-LAST:event_aMCNPJActionPerformed

    private void aMSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMSelActionPerformed
        this.mercado = mercados.get(this.aMSel.getSelectedIndex());
        String box = Integer.toString(mercado.getTotalBox());
        this.aMCNPJ.setText(mercado.getCnpj());
        this.aMNome.setText(mercado.getNome());
        this.aMNomef.setText(mercado.getNomeFantasia());
        this.aMEndereco.setText(mercado.getEndereco());
        this.aMTBox.setText(box);
    }//GEN-LAST:event_aMSelActionPerformed

    private void aMAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMAlActionPerformed
        PrefeituraDAO prefeituraDAO = new PrefeituraDAO();
        List <Prefeitura> prefeituras = prefeituraDAO.listar();
        String cnpj = prefeituras.get(0).getCnpj();
        int totalBox = Integer.parseInt(this.aMTBox.getText());
        mercado = new Mercado(aMCNPJ.getText(), aMNome.getText(), aMNomef.getText(),
        aMEndereco.getText(), totalBox, cnpj);
        mercadoDAO.alterar(mercado);
        JOptionPane.showMessageDialog(null, "Mercado: \n" + mercado + "\nAlteração realizada com sucesso!");
        this.dispose();
    }//GEN-LAST:event_aMAlActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {  
            mercadoDAO.excluir(this.aMCNPJ.getText());
            JOptionPane.showMessageDialog(null, "Mercado: \n" + this.mercado + "\n Excluído com sucesso!");
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex.getMessage());
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aMAl;
    private javax.swing.JFormattedTextField aMCNPJ;
    private javax.swing.JButton aMCanc;
    private javax.swing.JTextField aMEndereco;
    private javax.swing.JTextField aMNome;
    private javax.swing.JTextField aMNomef;
    private javax.swing.JComboBox<String> aMSel;
    private javax.swing.JTextField aMTBox;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
